[project]
name = "kindness-protocol"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.connections]
path = "contracts/connections.clar"

[contracts.kindness-protocol]
path = "contracts/kindness-protocol.clar"

[contracts.math]
path = "contracts/math.clar"

[contracts.sip-009]
path = "contracts/sip-009.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
